// <auto-generated />
using Anet.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anet.Migrations.Migrations
{
    [DbContext(typeof(AkkaMigrationContext))]
    partial class AkkaMigrationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anet.Db.Model.Akka.Journal", b =>
                {
                    b.Property<long>("Ordering")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ordering");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Ordering"));

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Manifest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manifest");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<string>("PersistenceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persistence_id");

                    b.Property<long>("SequenceNr")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_nr");

                    b.Property<int?>("SerializerId")
                        .HasColumnType("integer")
                        .HasColumnName("serializer_id");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.HasKey("Ordering");

                    b.HasIndex("PersistenceId", "SequenceNr")
                        .IsUnique();

                    b.ToTable("event_journal", "akka");
                });

            modelBuilder.Entity("Anet.Db.Model.Akka.Metadata", b =>
                {
                    b.Property<string>("PersistenceId")
                        .HasColumnType("text")
                        .HasColumnName("persistence_id");

                    b.Property<long>("SequenceNr")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_nr");

                    b.HasKey("PersistenceId", "SequenceNr");

                    b.ToTable("metadata", "akka");
                });

            modelBuilder.Entity("Anet.Db.Model.Akka.Snapshot", b =>
                {
                    b.Property<string>("PersistenceId")
                        .HasColumnType("text")
                        .HasColumnName("persistence_id");

                    b.Property<long>("SequenceNr")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_nr");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Manifest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manifest");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<int?>("SerializerId")
                        .HasColumnType("integer")
                        .HasColumnName("serializer_id");

                    b.HasKey("PersistenceId", "SequenceNr");

                    b.ToTable("snapshot_store", "akka");
                });
#pragma warning restore 612, 618
        }
    }
}
